#!/bin/bash

TECHNOLOGY=jvm
CONTAINERNAME=build-${TECHNOLOGY}

JAVA_VERSION=8
GRADLE_VERSION=4.0.2
SBT_VERSION=0.13.16

echo Building Build-Container ${CONTAINERNAME}:${JAVA_VERSION} including SBT-${SBT_VERSION} and Gradle-${GRADLE_VERSION}

docker build -t ${CONTAINERNAME}:${JAVA_VERSION} --build-arg JAVA_VERSION=${JAVA_VERSION} --build-arg SBT_VERSION=${SBT_VERSION} --build-arg GRADLE_VERSION=${GRADLE_VERSION} .

